version: "3.5"

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testdb"
    volumes:
      - project:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - cloud
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  cloud:
    container_name: cloud
    build:
      context: .
      dockerfile: Dockerfile
    image: cloud:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      DATABASESERVER_PORT: "5432"
    depends_on:
      - postgres
    networks:
      - cloud
networks:
  cloud:
    name: network_name
volumes:
  project:
    driver: local
  pgadmin-data:
    driver: local